import { Article } from './types';

const articles: Article[] = [
  {
    id: 18,
    title: 'React Hooks',
    date: 'April 2024',
    link: 'https://medium.com/@sullivanyoung/react-hooks-3dd20bc8c51a',
    image: 'https://miro.medium.com/v2/resize:fit:640/format:webp/1*TnxfhhGPVWSMi_ldbWWusA.jpeg',
  },
  {
    id: 17,
    title: 'What is Stripe?',
    date: 'October 2023',
    link: 'https://medium.com/@sullivanyoung/what-is-stripe-19f5b046f0b9',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*EWX-2AsYJ5JtKCBR0bY9EA.png',
  },
  {
    id: 16,
    title: 'How I Ended Up Managing a Small Esports Organization',
    date: 'October 2023',
    link: 'https://medium.com/@sullivanyoung/how-i-ended-up-managing-a-small-esports-organization-33ded5e00888',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*6q9WuDYMidwoYr4uJ9d4yA.png',
  },
  {
    id: 15,
    title: '5 Tools To Build and Break Habits',
    date: 'September 2023',
    link: 'https://medium.com/@sullivanyoung/5-tools-to-build-and-break-habits-6f367aedc965',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*MNS-dt0Uuob3pRmsFIAWaQ.png',
  },
  {
    id: 14,
    title: 'Everything You Should Know About Investing',
    date: 'September 2023',
    link: 'https://medium.com/@sullivanyoung/everything-you-should-know-about-investing-74914d1f4195',
    image: 'https://miro.medium.com/v2/resize:fit:640/format:webp/1*TA6IBjXPEvdht_N3H1es2Q.jpeg',
  },
  {
    id: 13,
    title: 'Life Lessons From Uncle Iroh',
    date: 'September 2023',
    link: 'https://medium.com/@sullivanyoung/life-lessons-from-uncle-iroh-50dbc11a2171',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*FkBAqpytoE4YeMK6BIRwRA.png',
  },
  {
    id: 12,
    title: 'I Achieved a 600 Day Streak on Duolingo',
    date: 'September 2023',
    link: 'https://medium.com/@sullivanyoung/i-achieved-a-600-day-streak-on-duolingo-4ae8af30161b',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*6lu6oWiY8jY2W1qSB55zGg.png',
  },
  {
    id: 11,
    title: '5 Tools To Improve Your Focus',
    date: 'April 2023',
    link: 'https://medium.com/@sullivanyoung/5-tools-to-improve-your-focus-7020073f23f8',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*E_C0HsoFuarbDXQJKjaeIA.jpeg',
  },
  {
    id: 10,
    title: '5 Tools For Positivity',
    date: 'January 2023',
    link: 'https://medium.com/@sullivanyoung/5-tools-for-positivity-5b566ab98bb9',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*zE8jjX68nfihQPCN4Ynpqw.jpeg',
  },
  {
    id: 9,
    title: '5 (More) Tools To Master Your Sleep',
    date: 'January 2023',
    link: 'https://medium.com/@sullivanyoung/5-more-tools-to-master-your-sleep-47520ac3d9eb',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*MI1H1T7Rn7qoy_N3zEnV-A.jpeg',
  },
  {
    id: 8,
    title: '5 Tools To Master Your Sleep',
    date: 'January 2023',
    link: 'https://medium.com/@sullivanyoung/5-tools-to-master-your-sleep-529ad5dee004',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*MI1H1T7Rn7qoy_N3zEnV-A.jpeg',
  },
  {
    id: 7,
    title: 'APIs For-5-Year-Olds',
    date: 'December 2022',
    link: 'https://medium.com/@sullivanyoung/apis-for-5-year-olds-3c5a694e5932',
    image: 'https://miro.medium.com/v2/resize:fit:640/format:webp/1*8nRtM8wRD7sjbCxYfb0JJw.jpeg',
  },
  {
    id: 6,
    title: 'How The Web Works',
    date: 'December 2022',
    link: 'https://medium.com/@sullivanyoung/how-the-web-works-8445d7d965c1',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*gZyWpsnhvlFFeMfGzjsd4Q.jpeg',
  },
  {
    id: 5,
    title: 'React Full Dive: Functional vs Class Based Components',
    date: 'December 2022',
    link: 'https://medium.com/@sullivanyoung/react-full-dive-functional-vs-class-based-components-e1dae3336ebb',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/0*saFYMr-blcu-bwct.png',
  },
  {
    id: 4,
    title: 'What really is JavaScript?',
    date: 'December 2022',
    link: 'https://medium.com/@sullivanyoung/what-really-is-javascript-origins-and-the-basics-1b4914f355ed',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*wzdbcyGYRmVROsB6GaKSKQ.png',
  },
  {
    id: 3,
    title: 'React Full Dive: JSX',
    date: 'November 2022',
    link: 'https://medium.com/@sullivanyoung/react-full-dive-under-the-hood-a0cffb5f87af',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*IoCLrnfGa9GzPimOovQyDg.png',
  },
  {
    id: 2,
    title: 'React Full Dive: The Basics',
    date: 'November 2022',
    link: 'https://medium.com/@sullivanyoung/react-full-dive-the-basics-ef2b858face',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*IoCLrnfGa9GzPimOovQyDg.png',
  },
  {
    id: 1,
    title: 'How I became a Software Engineer',
    date: 'November 2022',
    link: 'https://medium.com/@sullivanyoung/how-i-became-a-software-engineer-without-a-computer-science-degree-4b4bdeba68a',
    image: 'https://miro.medium.com/v2/resize:fit:720/format:webp/1*zDsgMyfArvziVfV9GZeQOA.png',
  },
];

export default articles;
